title = "Tire-allaite moi"
baseURL = 'http://example.org/'
languageCode = 'fr-FR'
theme = 'learts'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fr]
    title = "Tire-allaite moi"
    weight = 1
    contentDir = "content"
#  [languages.en]
#    title = "Tire-allaite moi"
#    weight = 2
#    contentDir = "content/en"

[permalinks]
  [permalinks.page]
    post = '/articles/:slug/'
  [permalinks.section]
    post = '/articles/'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
[params]
  text_color = ""
  author = "Son Ca DESTRIEUX"
  email = "contact@tire-allaite-moi.fr"
  favicon = ""
  site_logo = "/images/logo/logo-2.webp"
  footer_logo = "/images/logo/logo-2.webp"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

    [[params.socials]]
        name = "twitter"
        url = "https://twitter.com/theNewDynamic"
        icon = "twitter"
    [[params.socials]]
        name = "facebook"
        url = "https://twitter.com/theNewDynamic"
        icon = "facebook"

[menu]
    [[menu.main]]
        name = 'Accueil'
        pageRef = '/'
        weight = 99
    [[menu.main]]
        name = 'À propos de moi'
        pageRef = '/about'
        weight = 0
