title = "Tire-allaite moi"
baseURL = 'https://www.tire-allaite-moi.com/'
languageCode = 'fr-FR'
theme = 'learts'

DefaultContentLanguage = "fr"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fr]
    title = "Tire-allaite moi"
    weight = 1
    contentDir = "content"
#  [languages.en]
#    title = "Tire-allaite moi"
#    weight = 2
#    contentDir = "content/en"

[permalinks]
  [permalinks.page]
    post = '/articles/:slug/'
    page = '/:slug'
  [permalinks.section]
    post = '/articles'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Son Ca DESTRIEUX"
  email = "contact@tire-allaite-moi.fr"
  favicon = ""
  textual_logo = "/images/logo/logo-2.webp"
  small_logo = "/images/logo/logo-2.webp"
  big_logo = "/images/logo/logo-2.webp"
  site_logo = "/images/logo/logo-2.webp"
  footer_logo = "/images/logo/logo-2.webp"
  description = "[TODO]"

    [[params.socials]]
        name = "instagram"
        url = "https://www.instagram.com/tire.allaite.moi"
        icon = "instagram"
    [[params.socials]]
        name = "facebook"
        url = "https://www.facebook.com/tire.allaite.moi"
        icon = "facebook"

[menu]
    [[menu.main]]
        name = 'Accueil'
        pageRef = '/'
    [[menu.main]]
        name = 'Articles'
        pageRef = '/post'
    [[menu.main]]
        name = 'À propos de moi'
        pageRef = '/about'
