backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  squash_merges: true
publish_mode: editorial_workflow # beta editorial mode, for drafts and reviewing statuses
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: articles/{{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "pulished_at", widget: "datetime"}
      - {label: "Image d'illustration", name: "thumbnail", widget: "image"}
      - {label: "Apperçu", name: "excerpt", widget: "text"}
      - {label: "Contenu", name: "body", widget: "markdown"}
